name: 'Build Image'
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: actions/checkout@v3
      - run: docker build . --file Dockerfile --tag ghcr.io/mattmhersh/testapp:1.0
      - run:  echo ${{ secrets.PAT }} | docker login ghcr.io -u mattmhersh --password-stdin
      - run:  docker push ghcr.io/mattmhersh/testapp:1.0

